#theme:  jekyll-theme-leap-day  # tentei minimal mas não deu certo

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-avatar
logo: /logo.png
title: Fronteiras da Engenharia de Software
description: um podcast de divulgação científica associadao ao Programa de Pós-Graduação em Computação Aplicada (PPGCA) da UTFPR Curitiba e ao Emílias - Armação em Bits (somos parte da Rede Emílias de Podcasts).
 
twitter_username: fronteirases # DO NOT include the @ character, or else the build will fail!
github_username:  fronteirases # DO NOT include the @ character, or else the build will fail!
instagram_username: fronteirases

relative_links:
  enabled: true
  collections: true
include:
  - index.md


